import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillInstagram, AiFillLinkedinCricle,AiFillLinkedin} from 'react-icons/ai'
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import desgin from '../public/design.png';
import code from '../public/code.png';
import consluting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Manu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 md:px-20 lg:px-40 dark:bg-black dark:text-white transition-all '   >

      <section className=' min-h-screen ' >
        <nav  className="py-10 mb-12 flex justify-between lg:py-6" >
            <h1 className='text-xl font-burtons' >Welcome!</h1>
          <ul className='flex items-center gap-2'>
            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='text-2xl cursor-pointer' /></li>
            <li><a className=  ' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-5 py-2 rounded-md ml-2' href="#">Resume</a></li>
          </ul>
        </nav>
        <div className='relative  bg-gradient-to-b from-teal-500 to-teal-700 mx-auto mb-2 rounded-full w-60 h-60 mt-20 overflow-hidden' >
          <Image src={deved} className="absolute bottom-0 bg-cover "  />
        </div>
        <div className='text-center p-10' >
          <h2 className='text-5xl font-medium text-teal-500 md:text-6xl'>Manu</h2>
          <h3 className='text-2xl py-2 md:text-3xl'>Web Developer</h3>
          <p className='text-xl ' >Freelancer </p>
        </div>
        <div className='text-5xl flex justify-center gap-4 py-3 lg:py-1'>
         <AiFillTwitterCircle/>
         <AiFillInstagram/>
         <AiFillLinkedin/>
        </div>
       
      </section>

      <section>
        <div>
          <h3 className='text-3xl py-1' >Services I Offer</h3>
          <p className='text-md py-2 leading-6 text-gray-500 '> Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia ea ipsa tenetur delectus voluptatem, nam qui incidunt voluptate tempore voluptatum!</p>
        </div>

      <div className='lg:flex gap-10 justify-center'>
      <div className='text-center  shadow-lg p-10 mt-10 rounded-lg  '>
        <Image src={desgin} width={100} height={100} className='inline-block mt-2'/>
        <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
      </div>
      <div className='text-center  shadow-lg p-10 mt-10 rounded-lg  '>
        <Image src={code} width={100} height={100} className='inline-block mt-2'/>
        <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
      </div>
      <div className='text-center  shadow-lg p-10 mt-10 rounded-lg  '>
        <Image src={consluting} width={100} height={100} className='inline-block mt-2'/>
        <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
      </div>
      </div>

      </section>
    
      <section>
        <div>
          <h3 className='text-3xl py-2'>Portfolio</h3>
        </div>
      <div   className='flex flex-col gap-10 py-10  lg:flex-row lg:flex-wrap '   >

        <div className='basis-1/3 flex-1' >
          <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'}  />
        </div>
        <div className='basis-1/3 flex-1' >
          <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'}  />
        </div>
        <div className='basis-1/3 flex-1' >
          <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'}  />
        </div>
        <div className='basis-1/3 flex-1' >
          <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'}  />
        </div>
        <div className='basis-1/3 flex-1' >
          <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'}  />
        </div>
        <div className='basis-1/3 flex-1' >
          <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'}  />
        </div>
        </div>
      </section>
      
      </main>
    </div>
  )
}
